#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(TASKHOG_EVENTS);

typedef enum {
    TASKHOG_EVENT_BOOT_COMPLETE = 0,
    TASKHOG_EVENT_STATE_CHANGED,
    TASKHOG_EVENT_REC_PRESS,
    TASKHOG_EVENT_REC_RELEASE,
    TASKHOG_EVENT_REC_DISCARD,
    TASKHOG_EVENT_FINALIZE_DONE,
    TASKHOG_EVENT_CONFIRM_DONE,
    TASKHOG_EVENT_RECORD_MAX,
    TASKHOG_EVENT_SYNC_REQUEST,
    TASKHOG_EVENT_SYNC_DONE,
    TASKHOG_EVENT_PROVISION_REQUEST,
    TASKHOG_EVENT_PROVISION_DONE,
    TASKHOG_EVENT_OTA_REQUEST,
    TASKHOG_EVENT_OTA_DONE,
    TASKHOG_EVENT_BATTERY_LOW,
    TASKHOG_EVENT_ERROR,
} taskhog_event_id_t;
